version: '3.5'
services:
  web:
    hostname: web
    image: api.simple2do.xyz
    links:
      - redis:redis
    env_file: ./src/todo_list/.env
    command: gunicorn todo_list.wsgi -w 2 -b unix:/tmp/socket/api.sock -t 300
    volumes:
      - ./nginx/socket/:/tmp/socket/
  redis:
    hostname: redis
    image: redis:latest
  nginx:
    hostname: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/socket/:/tmp/socket/
      - ./nginx/data/certbot/conf:/etc/letsencrypt
      - ./nginx/data/certbot/www:/var/www/certbot
    #   - /etc/letsencrypt/:/etc/letsencrypt/
    #   - /etc/chronograf/:/etc/chronograf/
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    links:
      - web:web
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/data/certbot/conf:/etc/letsencrypt
      - ./nginx/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
