# Generated by Django 2.2.17 on 2020-12-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todotask',
            old_name='archvied_at',
            new_name='archived_at',
        ),
    ]
