# Generated by Django 2.2.17 on 2020-12-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20201210_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotask',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='done_at',
        ),
        migrations.AddField(
            model_name='todotask',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
